server:
  port: 44001
spring:
  application:
    name: test\u2010rabbitmq\u2010consumer
  rabbitmq:
    host: 192.168.118.130
    port: 5672
    username: guest
    password: guest
    virtualHost: /

