server:
  port: 31200
spring:
  application:
    name: xc-service-manage-course
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/xc_course?characterEncoding=utf-8
      username: root
      password: mysql
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  pagehelper:
    helper‐dialect: mysql

ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000 #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: http://localhost:50101/eureka/

# 配置详情页面发布所需要用到的数据
course-publish:
  # 以下为详情页的通用数据,所有的详情页所对应的详情页站点id和详情页模板都是相同的 其他的地方(获取数据的url需要和课程的id结合,因为每一个都不同)
  siteId: 5de88000537b187cefcfe891  # 详情页用到的站点id
  templateId: 5de87a29537b187cefcfe880  # 详情页搭配的模板id
  previewUrl: http://www.xuecheng.com/cms/preview/  # 详情页所用到的预览url
  pageWebPath: /course/detail/
  pagePhysicalPath: course/detail/  # 用来拼接路径的分段url
  dataUrlPre: http://localhost:31200/course/courseview/  # 获取详情页数据的url(从mysql中获取)